# Generated by Django 5.0.7 on 2025-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPCESections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250)),
                ('service_provided', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='./static/images/mpce_services')),
                ('opening_hours', models.TimeField(null=True)),
                ('closing_hours', models.TimeField(null=True)),
            ],
        ),
    ]
