# Generated by Django 5.0.7 on 2025-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpce_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcesections',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpcesections',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
