# Generated by Django 5.0.7 on 2025-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpce_services', '0002_alter_mpcesections_closing_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcesections',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
