# Generated by Django 5.0.7 on 2025-07-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.CharField(db_column='CategoryId', max_length=50, primary_key=True, serialize=False)),
                ('categorycode', models.CharField(blank=True, db_column='CategoryCode', max_length=50, null=True)),
                ('categoryshortname', models.CharField(blank=True, db_column='CategoryShortName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('loanrequestid', models.CharField(db_column='LoanRequestId', max_length=50, primary_key=True, serialize=False)),
                ('loanrequestcode', models.CharField(blank=True, db_column='LoanRequestCode', max_length=50, null=True)),
                ('loanrequeststatusid', models.CharField(blank=True, db_column='LoanRequestStatusId', max_length=50, null=True)),
                ('requestedbyid', models.CharField(blank=True, db_column='RequestedById', max_length=50, null=True)),
                ('requestdate', models.DateTimeField(blank=True, db_column='RequestDate', null=True)),
                ('modelid', models.CharField(blank=True, db_column='ModelId', max_length=50, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('personnelid', models.CharField(blank=True, db_column='PersonnelId', max_length=50, null=True)),
                ('siteid', models.CharField(blank=True, db_column='SiteId', max_length=50, null=True)),
                ('locationid', models.CharField(blank=True, db_column='LocationId', max_length=50, null=True)),
                ('organisationid', models.CharField(blank=True, db_column='OrganisationId', max_length=50, null=True)),
                ('branchid', models.CharField(blank=True, db_column='BranchId', max_length=50, null=True)),
                ('teamid', models.CharField(blank=True, db_column='TeamId', max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('loanrequestnotes', models.TextField(blank=True, db_column='LoanRequestNotes', null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='CreationDate', null=True)),
                ('modificationdate', models.DateTimeField(blank=True, db_column='ModificationDate', null=True)),
                ('requestedfor', models.CharField(blank=True, db_column='RequestedFor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LoanRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.CharField(db_column='LocationId', max_length=50, primary_key=True, serialize=False)),
                ('locationcode', models.CharField(blank=True, db_column='LocationCode', max_length=50, null=True)),
                ('locationshortname', models.CharField(blank=True, db_column='LocationShortName', max_length=255, null=True)),
                ('locationlongname', models.TextField(blank=True, db_column='LocationLongName', null=True)),
                ('locationdescription', models.TextField(blank=True, db_column='LocationDescription', null=True)),
                ('inactive', models.BooleanField(blank=True, db_column='Inactive', null=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locationtype',
            fields=[
                ('locationtypeid', models.CharField(db_column='LocationTypeId', max_length=50, primary_key=True, serialize=False)),
                ('locationtypecode', models.CharField(blank=True, db_column='LocationTypeCode', max_length=50, null=True)),
                ('locationtypeshortname', models.CharField(blank=True, db_column='LocationTypeShortName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LocationType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelid', models.CharField(db_column='ModelId', max_length=50, primary_key=True, serialize=False)),
                ('modelcode', models.CharField(blank=True, db_column='ModelCode', max_length=50, null=True)),
                ('modelshortname', models.CharField(blank=True, db_column='ModelShortName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.CharField(db_column='SiteId', max_length=50, primary_key=True, serialize=False)),
                ('sitecode', models.CharField(blank=True, db_column='SiteCode', max_length=50, null=True)),
                ('siteshortname', models.CharField(blank=True, db_column='SiteShortName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_model_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('equip_model_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='./static/images/model')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_models', to='library_app.equipmentmodel')),
            ],
        ),
    ]
