# Generated by Django 5.0.7 on 2025-07-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
