# Generated by Django 5.0.7 on 2025-10-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_equipmentmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='peremant_item',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
