# Generated by Django 5.0.7 on 2025-10-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_equipmentmodel_peremant_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentmodel',
            old_name='equip_model_id',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='equip_model_name',
        ),
    ]
