# Generated by Django 5.0.7 on 2025-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_rename_equip_model_id_equipmentmodel_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='peremant_item',
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='permenant_loan',
            field=models.BooleanField(default=False, verbose_name='Permenant loan to wards.'),
        ),
    ]
