# Generated by Django 5.2.9 on 2026-01-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_equipmentmodel_peremant_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='category_name',
            field=models.CharField(default='library itme', max_length=250),
            preserve_default=False,
        ),
    ]
