# Generated by Django 5.2.9 on 2026-01-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_equipmentmodel_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentModel',
            new_name='LoanCategory',
        ),
    ]
