# Generated by Django 5.2.9 on 2026-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_rename_equipmentmodel_loancategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancategory',
            old_name='permenant_loan',
            new_name='is_permanent_loan',
        ),
        migrations.AddField(
            model_name='loancategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
