# Generated by Django 5.2.9 on 2026-02-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_rename_permenant_loan_loancategory_is_permanent_loan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancategory',
            options={'permissions': [('manage_loan_categories', 'Can manage loan categories')]},
        ),
    ]
