# Generated by Django 5.0.7 on 2025-11-25 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_location_id', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=100, unique=True)),
                ('machine_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_picture', models.ImageField(upload_to='./static/images/ultrasound')),
                ('last_qa_date', models.DateField(blank=True, null=True)),
                ('next_qa_date', models.DateField(blank=True, editable=False, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cusas_app.locations')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTesters',
            fields=[
                ('testers_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cusas_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_date', models.DateField()),
                ('general_fault', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, choices=[('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Completed successfully')], default='NS', max_length=100, null=True)),
                ('equip_job_no', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusas_app.machine')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusas_app.machinetesters')),
            ],
        ),
        migrations.CreateModel(
            name='Probes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('probes_model', models.CharField(max_length=200)),
                ('probes_SN', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusas_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='QASchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_schedules', to='cusas_app.locations')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_schedules', to='cusas_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_bool', models.BooleanField(blank=True, null=True)),
                ('uniformity', models.TextField(blank=True, null=True)),
                ('depth_reverb', models.FloatField(blank=True, null=True)),
                ('noise_level_gain_value', models.FloatField(blank=True, null=True)),
                ('log_faults', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, choices=[('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Completed successfully')], default='NS', max_length=100, null=True)),
                ('result_date', models.DateField()),
                ('equip_job_no', models.IntegerField(blank=True, null=True)),
                ('probes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusas_app.probes')),
                ('testers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusas_app.machinetesters')),
            ],
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['asset_number'], name='cusas_app_m_asset_n_74d688_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['location'], name='cusas_app_m_locatio_a3edd0_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['next_qa_date'], name='cusas_app_m_next_qa_4af477_idx'),
        ),
        migrations.AddIndex(
            model_name='qaschedule',
            index=models.Index(fields=['machine', 'location'], name='cusas_app_q_machine_d41497_idx'),
        ),
        migrations.AddIndex(
            model_name='qaschedule',
            index=models.Index(fields=['is_active'], name='cusas_app_q_is_acti_859b58_idx'),
        ),
        migrations.AddIndex(
            model_name='qaschedule',
            index=models.Index(fields=['effective_from', 'effective_to'], name='cusas_app_q_effecti_e401bd_idx'),
        ),
    ]
