# Generated by Django 5.0.7 on 2025-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probes',
            name='probes_SN',
        ),
        migrations.AddField(
            model_name='probes',
            name='probe_equip_no',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
