# Generated by Django 5.0.7 on 2025-11-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0002_remove_probes_probes_sn_probes_probe_equip_no'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machine',
            new_name='cusas_app_m_equip_l_c40961_idx',
            old_name='cusas_app_m_locatio_a3edd0_idx',
        ),
        migrations.AlterField(
            model_name='locations',
            name='equip_location_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.ForeignKey(db_column='equip_location_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='cusas_app.locations', to_field='equip_location_id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
