# Generated by Django 5.0.7 on 2025-11-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cusas_app",
            "0003_rename_cusas_app_m_locatio_a3edd0_idx_cusas_app_m_equip_l_c40961_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qaschedule",
            options={
                "verbose_name": "QA schedule rule",
                "verbose_name_plural": "QA schedule rules",
            },
        ),
        migrations.RemoveIndex(
            model_name="qaschedule",
            name="cusas_app_q_machine_d41497_idx",
        ),
        migrations.RemoveField(
            model_name="qaschedule",
            name="location",
        ),
        migrations.AddField(
            model_name="qaschedule",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="qa_schedules", to="cusas_app.locations"
            ),
        ),
        migrations.AlterField(
            model_name="qaschedule",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qa_schedules",
                to="cusas_app.machine",
            ),
        ),
        migrations.AddIndex(
            model_name="qaschedule",
            index=models.Index(
                fields=["machine"], name="cusas_app_q_machine_035797_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="qaschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="qa_sched_window_ok",
            ),
        ),
    ]
