# Generated by Django 5.0.7 on 2025-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0004_alter_qaschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='asset_id',
            field=models.CharField(default=12312, max_length=250),
            preserve_default=False,
        ),
    ]
