# Generated by Django 5.0.7 on 2025-11-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0005_machine_asset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='asset_id',
            new_name='equip_equipment_id',
        ),
    ]
