# Generated by Django 5.0.7 on 2025-11-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0006_rename_asset_id_machine_equip_equipment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probes',
            old_name='probe_equip_no',
            new_name='equip_no',
        ),
        migrations.RenameField(
            model_name='probes',
            old_name='probes_model',
            new_name='probe_model',
        ),
    ]
