# Generated by Django 5.0.7 on 2025-12-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0007_rename_probe_equip_no_probes_equip_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('interval_days', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='cusas_app_s_is_acti_aca278_idx'), models.Index(fields=['effective_from', 'effective_to'], name='cusas_app_s_effecti_566b02_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationQASchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervals_days', models.PositiveBigIntegerField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='location_qa_schedules', to='cusas_app.locations')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_rules', to='cusas_app.standardschedule')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_qa_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='cusas_app.standardschedule'),
        ),
        migrations.DeleteModel(
            name='QASchedule',
        ),
        migrations.AddIndex(
            model_name='locationqaschedule',
            index=models.Index(fields=['is_active'], name='cusas_app_l_is_acti_a58398_idx'),
        ),
        migrations.AddIndex(
            model_name='locationqaschedule',
            index=models.Index(fields=['effective_from', 'effective_to'], name='cusas_app_l_effecti_a57604_idx'),
        ),
    ]
