# Generated by Django 5.0.7 on 2025-12-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0008_standardschedule_locationqaschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationqaschedule',
            old_name='intervals_days',
            new_name='interval_days',
        ),
        migrations.RemoveField(
            model_name='locationqaschedule',
            name='profile',
        ),
    ]
