# Generated by Django 5.0.7 on 2025-12-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0009_rename_intervals_days_locationqaschedule_interval_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='room',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_room',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='probes',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='cusas_app.machine'),
        ),
    ]
