# Generated by Django 5.0.7 on 2025-12-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cusas_app", "0010_remove_locations_room_machine_machine_room_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="machinetesters",
            old_name="service_id",
            new_name="service",
        ),
        migrations.RemoveField(
            model_name="machinetesters",
            name="testers_id",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_id",
        ),
        migrations.AddField(
            model_name="machinetesters",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machinetesters",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
