# Generated by Django 5.0.7 on 2025-12-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0012_remove_generalfault_tester_remove_testresult_testers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='visual_bool',
        ),
        migrations.AddField(
            model_name='testresult',
            name='visual_inspection',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visual Inspection'),
        ),
    ]
