# Generated by Django 5.0.7 on 2025-12-07 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cusas_app", "0013_remove_testresult_visual_bool_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult", old_name="probes", new_name="probe"
        )
    ]
