# Generated by Django 5.0.7 on 2025-12-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0014_rename_probes_to_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_picture',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_result', to='cusas_app.probes'),
        ),
    ]
