# Generated by Django 5.0.7 on 2025-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0015_alter_machine_machine_picture_alter_testresult_probe'),
    ]

    operations = [
        migrations.AddField(
            model_name='probes',
            name='equipment_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
