# Generated by Django 5.0.7 on 2025-12-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0016_probes_equipment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='equip_equipment_id',
            new_name='equipment_id',
        ),
    ]
