# Generated by Django 5.0.7 on 2025-12-12 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cusas_app", "0017_rename_equip_equipment_id_machine_equipment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeneralFault",
            new_name="Fault",
        )
    ]
