# Generated by Django 5.0.7 on 2025-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0018_fault_delete_generalfault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='progress',
        ),
        migrations.AddField(
            model_name='fault',
            name='equip_job_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
