# Generated by Django 5.0.7 on 2025-12-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0019_remove_fault_progress_fault_equip_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='cusas_app.probes'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='cusas_app.machine'),
        ),
    ]
