# Generated by Django 5.0.7 on 2025-12-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0020_fault_probe_alter_fault_machine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Probes',
            new_name='Probe',
        ),
    ]
