# Generated by Django 5.0.7 on 2025-12-12 21:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0021_rename_probes_probe'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='QA Tolerance for probe', max_digits=4),
        ),
    ]
