# Generated by Django 5.0.7 on 2025-12-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0023_testresult_is_baseline_alter_probe_tolerance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='equip_job_no',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='log_faults',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='progress',
        ),
    ]
