# Generated by Django 5.0.7 on 2025-12-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0024_remove_testresult_equip_job_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fault',
            old_name='general_fault',
            new_name='reported_fault',
        ),
        migrations.AlterField(
            model_name='probe',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe', to='cusas_app.machine'),
        ),
    ]
