# Generated by Django 5.0.7 on 2025-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0025_rename_general_fault_fault_reported_fault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='work_done',
            field=models.TextField(blank=True, null=True),
        ),
    ]
