# Generated by Django 5.0.7 on 2025-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0026_fault_work_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcode', models.CharField(blank=True, db_column='JobCode', max_length=50, null=True)),
                ('jobshortname', models.CharField(blank=True, db_column='JobShortName', max_length=255, null=True)),
                ('joblongname', models.TextField(blank=True, db_column='JobLongName', null=True)),
                ('jobdescription', models.TextField(blank=True, db_column='JobDescription', null=True)),
                ('jobnotes', models.TextField(blank=True, db_column='JobNotes', null=True)),
                ('jobissuedate', models.DateTimeField(blank=True, db_column='JobIssueDate', null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='CreationDate', null=True)),
                ('caller', models.CharField(blank=True, db_column='Caller', max_length=255, null=True)),
                ('callertel', models.CharField(blank=True, db_column='CallerTel', max_length=50, null=True)),
                ('techcontactid', models.CharField(blank=True, db_column='TechContactId', max_length=50, null=True)),
                ('reportedfault', models.TextField(blank=True, db_column='ReportedFault', null=True)),
                ('faultfound', models.TextField(blank=True, db_column='FaultFound', null=True)),
                ('workdone', models.TextField(blank=True, db_column='WorkDone', null=True)),
                ('workstartdate', models.DateTimeField(blank=True, db_column='WorkStartDate', null=True)),
                ('workenddate', models.DateTimeField(blank=True, db_column='WorkEndDate', null=True)),
            ],
            options={
                'db_table': 'Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobstatus',
            fields=[
                ('jobstatusid', models.CharField(db_column='JobStatusId', max_length=50, primary_key=True, serialize=False)),
                ('jobstatuscode', models.CharField(blank=True, db_column='JobStatusCode', max_length=50, null=True)),
                ('jobstatusshortname', models.CharField(blank=True, db_column='JobStatusShortName', max_length=255, null=True)),
                ('jobstatuslongname', models.TextField(blank=True, db_column='JobStatusLongName', null=True)),
            ],
            options={
                'db_table': 'JobStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('jobtypeid', models.CharField(db_column='JobTypeId', max_length=50, primary_key=True, serialize=False)),
                ('jobtypecode', models.CharField(blank=True, db_column='JobTypeCode', max_length=50, null=True)),
                ('jobtypeshortname', models.CharField(blank=True, db_column='JobTypeShortName', max_length=255, null=True)),
                ('jobtypelongname', models.TextField(blank=True, db_column='JobTypeLongName', null=True)),
                ('jobtypedescription', models.TextField(blank=True, db_column='JobTypeDescription', null=True)),
                ('modificationdate', models.DateTimeField(blank=True, db_column='ModificationDate', null=True)),
                ('inactive', models.BooleanField(blank=True, db_column='Inactive', null=True)),
            ],
            options={
                'db_table': 'JobType',
                'managed': False,
            },
        ),
    ]
