# Generated by Django 5.0.7 on 2025-12-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0027_job_jobstatus_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='equip_job_status',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='fault_date',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='reported_fault',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='work_done',
        ),
        migrations.AlterField(
            model_name='fault',
            name='equip_job_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
