# Generated by Django 5.0.7 on 2025-12-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0028_remove_fault_equip_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='equip_job_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
