# Generated by Django 5.0.7 on 2025-12-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0029_alter_fault_equip_job_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobstatusclass',
            fields=[
                ('jobstatusclassid', models.CharField(db_column='JobStatusClassId', max_length=50, primary_key=True, serialize=False)),
                ('jobstatusclasscode', models.CharField(blank=True, db_column='JobStatusClassCode', max_length=50, null=True)),
                ('jobstatusclassshortname', models.CharField(blank=True, db_column='JobStatusClassShortName', max_length=255, null=True)),
                ('jobstatusclasslongname', models.TextField(blank=True, db_column='JobStatusClassLongName', null=True)),
                ('jobstatusclassdescription', models.TextField(blank=True, db_column='JobStatusClassDescription', null=True)),
            ],
            options={
                'db_table': 'JobStatusClass',
                'managed': False,
            },
        ),
    ]
