# Generated by Django 5.2.9 on 2026-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0030_jobstatusclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='room',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
