# Generated by Django 5.2.9 on 2026-02-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0030_jobstatusclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_picture',
        ),
    ]
