# Generated by Django 5.2.9 on 2026-02-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusas_app', '0031_locations_room'),
        ('cusas_app', '0031_remove_machine_machine_picture'),
    ]

    operations = [
    ]
