# Generated by Django 5.2.12 on 2026-05-12 20:26
from django.db import migrations

GROUPS = ["cusas_admin"]


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group_name in GROUPS:
        Group.objects.get_or_create(name=group_name)


class Migration(migrations.Migration):
    dependencies = [
        ("cusas_app", "0032_merge_20260223_1632"),
    ]
    operations = [migrations.RunPython(create_groups)]
